import type { CurrentUser, WorkFocus, WorkSession, Worker } from './types'

export const currentUser: CurrentUser = {
  id: 'me',
  name: 'You',
  initials: 'YO',
  role: 'Product Designer',
  status: 'available',
  focus: 'deep-work',
  isVisible: true,
}

export const focusLabels: Record<WorkFocus, string> = {
  'deep-work': 'Deep work',
  meetings: 'Meetings',
  admin: 'Admin & email',
  creative: 'Creative',
  learning: 'Learning',
  casual: 'Casual co-work',
}

export const focusEmoji: Record<WorkFocus, string> = {
  'deep-work': 'Focus',
  meetings: 'Calls',
  admin: 'Admin',
  creative: 'Making',
  learning: 'Study',
  casual: 'Casual',
}

export const workers: Worker[] = [
  {
    id: 'w1',
    name: 'Mara Ellis',
    role: 'Frontend Engineer',
    initials: 'ME',
    distanceMeters: 120,
    radar: { x: 0.18, y: -0.28 },
    status: 'focusing',
    focus: 'deep-work',
    headline: 'Shipping a big refactor before lunch.',
    focusingForMin: 42,
    hostingSessionId: 's1',
    area: 'Kadıköy waterfront',
  },
  {
    id: 'w2',
    name: 'Deniz Kaya',
    role: 'Freelance Writer',
    initials: 'DK',
    distanceMeters: 240,
    radar: { x: -0.42, y: 0.12 },
    status: 'available',
    focus: 'creative',
    headline: 'Drafting a newsletter, happy to chat on breaks.',
    focusingForMin: 15,
    area: 'Moda backstreets',
  },
  {
    id: 'w3',
    name: 'Sam Ortega',
    role: 'Data Analyst',
    initials: 'SO',
    distanceMeters: 310,
    radar: { x: 0.5, y: 0.34 },
    status: 'focusing',
    focus: 'deep-work',
    headline: 'Heads-down on a dashboard. Pomodoro mode.',
    focusingForMin: 8,
    area: 'Bahariye Ave',
  },
  {
    id: 'w4',
    name: 'Lena Fischer',
    role: 'UX Researcher',
    initials: 'LF',
    distanceMeters: 480,
    radar: { x: -0.3, y: -0.55 },
    status: 'available',
    focus: 'learning',
    headline: 'Taking a course, would love a study buddy.',
    focusingForMin: 25,
    hostingSessionId: 's2',
    area: 'Yeldeğirmeni',
  },
  {
    id: 'w5',
    name: 'Tomás Rocha',
    role: 'Indie Founder',
    initials: 'TR',
    distanceMeters: 620,
    radar: { x: 0.62, y: -0.5 },
    status: 'on-break',
    focus: 'casual',
    headline: 'Coffee break — ping me if you want company.',
    focusingForMin: 3,
    area: 'Rıhtım',
  },
  {
    id: 'w6',
    name: 'Priya Nair',
    role: 'Mobile Developer',
    initials: 'PN',
    distanceMeters: 780,
    radar: { x: -0.6, y: 0.5 },
    status: 'focusing',
    focus: 'deep-work',
    headline: 'Fixing a gnarly bug. Do not disturb until 3pm.',
    focusingForMin: 55,
    area: 'Söğütlüçeşme',
  },
]

export const sessions: WorkSession[] = [
  {
    id: 's1',
    title: 'Morning Deep Work Block',
    hostId: 'w1',
    focus: 'deep-work',
    place: 'Quiet cafe corner · Fabrika Coffee',
    area: 'Kadıköy waterfront',
    distanceMeters: 120,
    startsInMin: 20,
    durationMin: 90,
    capacity: 5,
    attendeeIds: ['w1', 'w3'],
    note: 'Silent focus, phones face-down. Short chat on the break.',
  },
  {
    id: 's2',
    title: 'Afternoon Study & Learn',
    hostId: 'w4',
    focus: 'learning',
    place: 'Library table · Nail Library',
    area: 'Yeldeğirmeni',
    distanceMeters: 480,
    startsInMin: 75,
    durationMin: 120,
    capacity: 4,
    attendeeIds: ['w4'],
    note: 'Learning together — bring headphones, we compare notes after.',
  },
  {
    id: 's3',
    title: 'Casual Co-work + Coffee',
    hostId: 'w5',
    focus: 'casual',
    place: 'Outdoor terrace · Moda Sahil',
    area: 'Rıhtım',
    distanceMeters: 620,
    startsInMin: 150,
    durationMin: 60,
    capacity: 6,
    attendeeIds: ['w5', 'w2'],
    note: 'Relaxed vibe, chatting welcome. Good for accountability, not silence.',
  },
]

export function getWorker(id: string): Worker | undefined {
  return workers.find((w) => w.id === id)
}
